---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.6.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53
    - --dns01-recursive-nameservers-only
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
      - "1.1.1.1"
      - "8.8.8.8"
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
        prometheusInstance: monitoring
