apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  # - le-staging.yaml
  # - le-prod.yaml
  - cloudflare-kabbags-co-api-token-secret.enc.yaml
