---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "joshrwolf14@gmail.com"
    privateKeySecretRef:
      name: le-prod
    solvers:
    - selector:
        dnsZones:
        - "kabbages.co"
      dns01:
        cloudflare:
          email: "joshrwolf14@gmail.com"
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
