---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: water
