apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-components.yaml
  - water.yaml
  - core.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    path: flux-patch.yaml
