---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: water
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/kabbages-co/water.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: water
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: water
    namespace: flux-system
