apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:1LuV6JtY6+mgqz14NaWyp4vMTG3AtEu45yzStB2TkO+gX7FzoIjfxA==,iv:9NUTTcTNI5E+U3p3011npRbj3ZHqjNO7CkqAnLxzFOU=,tag:m6g7ZkP1gQDLALPzGT1YZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-11-01T02:51:14Z'
    mac: ENC[AES256_GCM,data:t7nX37cc7dnfTWnilTkYcuBvNMj0mpy1HTG4zPX2rrt8lizFGqu3pdvsVLlieBPRDrZ2sCsr4vjIvUOCBeT7wwF0aLxvUZhw+NymVI/8bZalNoHDrEpAVKskqcFsIrKcmDI2dhFG5jxhUxi+nqckmYKjL0zs+EHQam8h5w8m6yw=,iv:QJVjNG4FfUfa0n0b8XNo0jX/aBVEIpBWsAP/WybYSdE=,tag:f6t6/d8+VCFbFZ2dtT1nog==,type:str]
    pgp:
    -   created_at: '2021-11-01T02:51:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwWTm8o+mcOPAQ/+J2RK0RkbiskNLfBawM3kLYuWWDnko4r2WWDfkvUSebv6
            qcM0PSe/eZ2JCKEh6vNl5BF/MP/Dm1ziqfkYafHnyVyOjKmVI6kBzs8mHNHi13MB
            PBz8Xm5eAzZuiPLoBflWsmNRVRa6ntIv8E44b5iGPGa07dLhu7RjA0nXhBj5Epwh
            vTiJk/owvYMvMBncjQFbwXVeHTaOiU0/hiZKE1wPfWhLnH8Mwwdkg+lgR4nvPDRN
            7mDWZ9++ovVuVzImD6HCq6Hy35z8peklogQDyNW5upnjuYLDsDN8VU+UfZn8z17c
            m9O5LMGEugKcj2yd8+cDNLrQW/AMbxrc6qe8Ee5/ytjLB2f0Dd8gzo1E5RFdzA1C
            rf+LVCNIL87lEdLI9c8/9ZN1BXyWyaGz/N1ZMUVjXcDZ4xLgPIGtcZvegAEVQ6KB
            ZZOToqHBeop4tC+gR8f0p4q1HuaCspHjDSfs1HU9WoX5edJBRXBFgHNZ2BKWlKA3
            2sqgfLNKkG5lxxlooU+CTJxdjrKgKadUhUkKNInazvOA3kWJGO4fKVG+xZfiihBS
            4+REjgGuLYOVhTQF/zoISb+6/xyvXqPlzKFIKY5gw/eK3yFrafBoEVGnBz/+KXha
            XuStAcJj2/0GvRaBpurgyifx5ZExLPRLxzs6jhyNYuKepsu88N3dpNvRoUwcBFnS
            XgFmsx3e5TM40wkw9alt2aGxa2ZIfhaSwqabes8NgjJjNuMI00+1dRrOFhmlQ8gq
            azkVNoEhiETU9fbQ/Nfm2RHq7YluFuUwQta6EuUTbQhutDK/L+juMXATokVoSaM=
            =OXOu
            -----END PGP MESSAGE-----
        fp: 70AA61670B7B6E24082AFE161766F2F52885306D
    -   created_at: '2021-11-01T02:51:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3O/Hgu1n9uEAQ/9EJZnLhnWHrFEGOOYH4rf/1f6mgENmO5kW5Ipk1Rsa2UU
            y13VVNrJHDHuAB/OuVcCuNb1ZmBMzfhTXMrK1H2zd/utpcRgJDgHYvR9g+epSps4
            aEW+o0ZoVttTdbgwS2VWdHoFNH21egJiINpcRTQA74xvbexq1JZj5qLTJ7IH1O6r
            GPsrqWQHo1+Hc6eTAdE5dxMzNIBZ25EWPZqzIb0hW1Lq/2yZV172G6BBw2Q6mQbe
            S7FLSIJpJNLQVpTTRHge43dZleF8Q2P+I4mMp6+LfpLybsPePDUNKF8gDTxURzM6
            UEA7fmnV9YPRzMniPtM9ESXv/yogM8pw0/obXTj8qf2RJtKuOLaAqiqxwIkKyf27
            aI+e+Fd9URlZ/20X++cAKNlzAIFbhenIiFdmANHuC78L+5ks2KKRced5w4uPmsJ6
            wQMa1o/qxvksUVBza+AW4AbEwKNmyVgzsTg/0XomWA/o5IEmjaVFOVN//NMEh4h4
            7yGHHf+jWK0ofmVuxIOjkwt9kbfqmElEUZOA6gpDhljKDVumbdRJV7T3xav/TCpI
            CZjOLt302kbzlnZEB9soGvWADhL7/Qlx6X5nKO9qzqNXHF/O8x+mXcDeTksDWC3k
            FoGKWSi4r3OgVNOaUVCJDOfXhBNCKzhd3DbHb8rXm9+6HnR8piyWJLWoFrwHOA/S
            XgEeSIydoQSu1j6g21ZNlRCZeo52HDprPhgJDeF40ylkgXvWgIcuMr6gPzodEcLF
            EM7tQYgwVQk/hiFewcSiH/MgZOnY1ChUDqMI19FiXffDZxr32lTwrt5nk6/6g7Q=
            =mT6o
            -----END PGP MESSAGE-----
        fp: 581CF216C56DE3E37B2A849DCBC7AEF8D170B40C
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
