---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  targetNamespace: external-dns
  chart:
    spec:
      chart: external-dns
      version: 5.4.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    metrics:
      enabled: true

    sources:
      - service
      - ingress

    provider: cloudflare

    cloudflare:
      secretName: cloudflare-api-token
