apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-kabbages-co
  namespace: cattle-system
spec:
  secretName: tls-rancher-ingress
  issuerRef:
    kind: ClusterIssuer
    name: le-prod
  dnsNames:
  - 'rancher.kabbages.co'
