---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: flux-system
spec:
  targetNamespace: cattle-system
  chart:
    spec:
      chart: rancher
      version: 2.6.2
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  values:
    hostname: rancher.kabbages.co

    bootstrapPassword: admin

    replicas: -1

    ingress:
      tls:
        source: secret

      extraAnnotations:
        external-dns.alpha.kubernetes.io/hostname: rancher.kabbages.co
        external-dns.alpha.kubernetes.io/ttl: "120" 

    letsEncrypt:
      ingress:
        class: traefik

