---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: flux-system
spec:
  targetNamespace: registry
  chart:
    spec:
      chart: docker-registry
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
  values:
    persistence:
      enabled: true
      size: 50Gi
    ingress:
      enabled: true
      hosts:
        - registry.kabbages.co
      annotations:
        cert-manager.io/cluster-issuer: "le-prod"
      tls:
        - hosts:
          - registry.kabbages.co
          secretName: registry-cert
